# --- Estágio 1: O Construtor (Builder) ---
FROM node:18 as builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# --- Estágio 2: A Imagem Final (Production) ---
FROM node:18-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package*.json ./
RUN npm install --omit=dev
COPY --from=builder /usr/src/app .

EXPOSE 3000
CMD [ "node", "index.js" ]